plugins {
    id 'com.android.application'
}

android {
    namespace 'com.athaya.bukukas'
    compileSdk 34

    defaultConfig {
        applicationId "com.athaya.bukukas"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    buildFeatures {
        viewBinding false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
